### ISSUE TITLE
MMD vs KSD

### ISSUE THREAD

**Issue by codgas** [jswu18/distribution-discrepancies#17]
First I would like to thank you for sharing this!, I have one technical questions: 
in the one of the experiments you preform , you showed that mmd converges to KSD , does that mean that compared to MMD ,KSD is a better for measuring the distance between between probability distributions  if you know the density function of one of them ?
if so do you have any references ?

**Comment by jswu18** [comment]
Hi there, thanks for reaching out!
I believe you're correct. In the setting of comparing a known density with samples from an unknown distribution, the KSD can be a better option. For example, if you check out Figure 2b in "A Linear-Time Kernel Goodness-of-Fit Test" from Jitkrittum, Xu et al, you can see that the KSD is able to detect much smaller perturbations. It incorporates knowledge of the density function unlike the MMD which is purely reliant on samples.
I hope this is helpful!
